<?php
header('Content-Type: text/html; charset=utf-8');
include "process.php";

$data = array(
	"title"=>"乐车仔商城首页",
	"description"=>"空调格 行车记录仪 汽车配件 汽车坐垫",
	"keywords"=>"空调格 行车记录仪 汽车配件 汽车坐垫",
	"login"=>"false",
	"url_regist"=>"注册的地址",
	"user"=>"用户账号",
	"url_orders"=>"order/",
	"cart_href"=>"#购物车页面地址",
	"usermenu"=>array(
		array(
			"href"=>"ucenter/#1",
			"blank"=>"_blank",
			"name"=>"账号中心",
			"other"=>""
		),
		array(
			"href"=>"#2",
			"blank"=>"_blank",
			"name"=>"服务中心",
			"other"=>""
		),
		array(
			"href"=>"",
			"blank"=>"",
			"name"=>"退出登陆",
			"other"=>"ng-click=\"logout();\""
		),
	),
	"topnav"=>array(
		array(
			"href"=>"http://www.baidu.com",
			"blank"=>"_self",
			"name"=>"百度",
			"title"=>"链接到百度",
			"cateid"=>"1"
		),
		array(
			"href"=>"http://www.126.com",
			"blank"=>"_blank",
			"name"=>"网易邮箱",
			"title"=>"网易邮箱",
			"cateid"=>"2"
		),
		array(
			"href"=>"http://www.lj2015.com",
			"blank"=>"_self",
			"name"=>"连奖2015",
			"title"=>"连奖新域名",
			"cateid"=>"3"
		),
		array(
			"href"=>"http://www.sina.com",
			"blank"=>"_blank",
			"name"=>"新浪",
			"title"=>"新浪首页",
			"cateid"=>"4"
		),
		array(
			"href"=>"http://www.163.com",
			"blank"=>"_self",
			"name"=>"网易",
			"title"=>"网易首页",
			"cateid"=>"5"
		),
		array(
			"href"=>"http://www.github.com",
			"blank"=>"_blank",
			"name"=>"GITHUB",
			"title"=>"GITHUB首页",
			"cateid"=>"6"
		),
	),
	"categories"=>array(
		array(
			"url"=>"#脚垫的地址",
			"name"=>"汽车脚垫",
			"alt"=>"用于SEO的优化字 of 脚垫",
			"subcates"=>array(
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫丝圈脚垫丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
			)
		),
		array(
			"url"=>"#空调格的地址",
			"name"=>"空调格",
			"alt"=>"用于SEO的优化字 of 空调格",
			"subcates"=>array(
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
			)
		),
	),
	"ppt"=>array(
		array(
			"url"=>"#1",
			"img"=>"http://www.new.com/index/ppt/ban1.png",
			"alt"=>"用于SEO的img的alt属性",
			"title"=>"图片1"
		),
		array(
			"url"=>"#2",
			"img"=>"http://www.new.com/index/ppt/ban2.png",
			"alt"=>"用于SEO的img的alt属性",
			"title"=>"图片2"
		),
	),
	"searchKeys"=>array(
		array(
			"name"=>"空调格",
			"title"=>"馨车仔空调过滤器",
			"href"=>"#"
		),
		array(
			"name"=>"云镜",
			"title"=>"畅车仔多功能云镜",
			"href"=>"#"
		),
		array(
			"name"=>"高级机油",
			"title"=>"劲车仔高级汽车润滑油",
			"href"=>"#"
		)
	),
	"funcs"=>array(
		"url_locate"=>"#url_locate",
		"url_package"=>"#url_package",
		"url_new"=>"#url_new",
		"url_down"=>"#url_down",
		"url_video"=>"#url_video"
	),
	"hots"=>array(
		"large"=>array(
			"href"=>"#linkurl",
			"name"=>"主推的大腕单品",
			"image"=>"/index/hots/star.png",
			"photo"=>"/index/hots/star2.png",
			"title"=>"优化用关键字",
			"price"=>1580
		),
		"list"=>array(
			array(
				"href"=>"#linkurl",
				"name"=>"主推的明星",
				"image"=>"/srcs/images/pro1.png",
				"title"=>"这里的很主要，但没大图重",
				"price"=>1000,
				"price0"=>1200,
				"summary"=>"可以不写的摘要可以不写的摘要可以不写的摘要",
				"signs"=>array(
					array(
						"type"=>"cutoff",
						"text"=>"打九折"
					),
					array(
						"type"=>"free",
						"text"=>"免邮费"
					),
				)
			),
			array(
				"href"=>"#linkurl",
				"name"=>"主推的明星",
				"image"=>"/srcs/images/pro2.png",
				"title"=>"这里的很主要，但没大图重",
				"price"=>1000,
				"summary"=>"可以不写的摘要",
				"signs"=>array(
					array(
						"type"=>"match",
						"text"=>"适配车型"
					),
					array(
						"type"=>"new",
						"text"=>"新品"
					),
				)
			),
			array(
				"href"=>"#linkurl",
				"name"=>"主推的明星",
				"image"=>"/srcs/images/pro3.png",
				"title"=>"这里的很主要，但没大图重",
				"price"=>1000,
				"price0"=>1200,
			),
			array(
				"href"=>"#linkurl",
				"name"=>"主推的明星",
				"image"=>"/srcs/images/pro4.png",
				"title"=>"这里的很主要，但没大图重",
				"price"=>1000,
				"signs"=>array(
					array(
						"type"=>"gift",
						"text"=>"有赠品"
					)
				)
			),
		)
	),
	"pushes"=>array(
		//第一块
		array(
			"mainname"=>"汽车坐垫",
			"subcates"=>array(
				array(
					"href"=>"#000",
					"title"=>"主要推荐的产品",
					"name"=>"热门"
				),
				array(
					"href"=>"#123",
					"title"=>"给小盆友坐的",
					"name"=>"儿童安全坐椅"
				),
				array(
					"href"=>"#456",
					"title"=>"边开车边按摩",
					"name"=>"成人按摩坐椅"
				),
				array(
					"href"=>"#666",
					"title"=>"本分类下的其它产品",
					"name"=>"查看更多"
				)
			),
			"left"=>array(
				"href"=>"#345",
				"title"=>"最新产品",
				"image"=>"/index/pushes/left.png"
			)
		)
	)
);


echo outputPage("index/index.html",$data);

