<?php
header('Content-Type: text/html; charset=utf-8');
include "process.php";

$data = array(
	"title"=>"乐车仔商品列表页",
	"description"=>"空调格 行车记录仪 汽车配件 汽车坐垫",
	"keywords"=>"空调格 行车记录仪 汽车配件 汽车坐垫",
	"login"=>"false",
	"url_regist"=>"注册的地址",
	"user"=>"用户账号",
	"url_orders"=>"order/",
	"cart_href"=>"#购物车页面地址",
	"usermenu"=>array(
		array(
			"href"=>"ucenter/#1",
			"blank"=>"_blank",
			"name"=>"账号中心",
			"other"=>""
		),
		array(
			"href"=>"#2",
			"blank"=>"_blank",
			"name"=>"服务中心",
			"other"=>""
		),
		array(
			"href"=>"",
			"blank"=>"",
			"name"=>"退出登陆",
			"other"=>"ng-click=\"logout();\""
		),
	),
	"topnav"=>array(
		array(
			"href"=>"http://www.baidu.com",
			"blank"=>"_self",
			"name"=>"百度",
			"title"=>"链接到百度",
			"cateid"=>"1"
		),
		array(
			"href"=>"http://www.126.com",
			"blank"=>"_blank",
			"name"=>"网易邮箱",
			"title"=>"网易邮箱",
			"cateid"=>"2"
		),
		array(
			"href"=>"http://www.lj2015.com",
			"blank"=>"_self",
			"name"=>"连奖2015",
			"title"=>"连奖新域名",
			"cateid"=>"3"
		),
		array(
			"href"=>"http://www.sina.com",
			"blank"=>"_blank",
			"name"=>"新浪",
			"title"=>"新浪首页",
			"cateid"=>"4"
		),
		array(
			"href"=>"http://www.163.com",
			"blank"=>"_self",
			"name"=>"网易",
			"title"=>"网易首页",
			"cateid"=>"5"
		),
		array(
			"href"=>"http://www.github.com",
			"blank"=>"_blank",
			"name"=>"GITHUB",
			"title"=>"GITHUB首页",
			"cateid"=>"6"
		),
	),
	"categories"=>array(
		array(
			"url"=>"#脚垫的地址",
			"name"=>"汽车脚垫",
			"alt"=>"用于SEO的优化字 of 脚垫",
			"subcates"=>array(
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫丝圈脚垫丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#丝圈脚垫地址",
					"name"=>"丝圈脚垫",
					"alt"=>"alt of 丝圈脚垫",
					"img"=>"/srcs/images/pro.png"
				),
			)
		),
		array(
			"url"=>"#空调格的地址",
			"name"=>"空调格",
			"alt"=>"用于SEO的优化字 of 空调格",
			"subcates"=>array(
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
				array(
					"url"=>"#空调格地址",
					"name"=>"空调格",
					"alt"=>"alt of 空调格",
					"img"=>"/srcs/images/pro.png"
				),
			)
		),
	),
	"searchKeys"=>array(
		array(
			"name"=>"空调格",
			"title"=>"馨车仔空调过滤器",
			"href"=>"#"
		),
		array(
			"name"=>"云镜",
			"title"=>"畅车仔多功能云镜",
			"href"=>"#"
		),
		array(
			"name"=>"高级机油",
			"title"=>"劲车仔高级汽车润滑油",
			"href"=>"#"
		)
	),
	"crumbs"=>array(
		array(
			"text"=>"商城首页",
			"href"=>"index.php",
			"title"=>"乐车仔商城 优化关键字"
		),
		array(
			"text"=>"服务门店",
			"href"=>"locate.php",
			"title"=>"乐车仔门店 服务门店 门店定位"
		),
	),
	"filters"=>array(
		array(
			"name"=>"分类",
			"items"=>array(
				array(
					"name"=>"新车必备",
					"href"=>"",
					"title"=>"",
					"cur"=>true
				),
				array(
					"name"=>"汽车养护",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"车载电器",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"汽车电子",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"汽车装饰",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"汽车美容",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"原车配件",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"加装配件",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"改装部件",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"自驾生活",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"改装部件",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"自驾生活",
					"href"=>"",
					"title"=>""
				)
			)
		),
		array(
			"name"=>"子分类",
			"items"=>array(
				array(
					"name"=>"汽车坐垫",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"专用脚垫",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"方向盘套",
					"href"=>"",
					"title"=>"",
					"cur"=>true
				),
				array(
					"name"=>"头枕/颈枕",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"空调被/抱枕",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"后备箱垫",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"车用竹炭",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"底盘装甲",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"雨刮精",
					"href"=>"",
					"title"=>""
				),
				array(
					"name"=>"充电器",
					"href"=>"",
					"title"=>""
				),
			)
		)
	),
	"pros"=>array(
		array(
			"id"=>1,
			"href"=>"#linkurl",
			"name"=>"第一产品首图",
			"image"=>"/srcs/images/pro.png",
			"title"=>"最开始默认显示产品第一配置",
			"price"=>1000,
			"price0"=>1200,
			"signs"=>array(
				array(
					"type"=>"match",
					"text"=>"适配车型"
				),
				array(
					"type"=>"new",
					"text"=>"新品"
				),
			),
			"thumbs"=>array(
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>800,
					"price0"=>1000,
					"signs"=>"free:包邮;cutoff:优惠9折"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro1.png",
					"photo"=>"/srcs/images/pro1.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro4.png",
					"photo"=>"/srcs/images/pro4.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro3.png",
					"photo"=>"/srcs/images/pro3.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"photo"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
			)
		),
		array(
			"id"=>2,
			"href"=>"#linkurl",
			"name"=>"第一产品首图",
			"image"=>"/srcs/images/pro.png",
			"title"=>"最开始默认显示产品第一配置",
			"price"=>1000,
			"price0"=>1200,
			"signs"=>array(
				array(
					"type"=>"match",
					"text"=>"适配车型"
				),
				array(
					"type"=>"new",
					"text"=>"新品"
				),
			),
			"thumbs"=>array(
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro4.png",
					"photo"=>"/srcs/images/pro4.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro3.png",
					"photo"=>"/srcs/images/pro3.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"photo"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
			)
		),
		array(
			"id"=>3,
			"href"=>"#linkurl",
			"name"=>"第一产品首图",
			"image"=>"/srcs/images/pro.png",
			"title"=>"最开始默认显示产品第一配置",
			"price"=>1000,
			"price0"=>1200,
			"signs"=>array(
				array(
					"type"=>"match",
					"text"=>"适配车型"
				),
				array(
					"type"=>"new",
					"text"=>"新品"
				),
			),
			"thumbs"=>array(
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro1.png",
					"photo"=>"/srcs/images/pro1.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro4.png",
					"photo"=>"/srcs/images/pro4.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro3.png",
					"photo"=>"/srcs/images/pro3.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"photo"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
			)
		),
		array(
			"id"=>4,
			"href"=>"#linkurl",
			"name"=>"第一产品首图",
			"image"=>"/srcs/images/pro.png",
			"title"=>"最开始默认显示产品第一配置",
			"price"=>1000,
			"price0"=>1200,
			"signs"=>array(
				array(
					"type"=>"match",
					"text"=>"适配车型"
				),
				array(
					"type"=>"new",
					"text"=>"新品"
				),
			),
			"thumbs"=>array(
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro.png",
					"photo"=>"/srcs/images/pro.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"photo"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
				array(
					"href"=>"#linkurl",
					"cart"=>"#url for put into cart",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro1.png",
					"photo"=>"/srcs/images/pro1.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
					"signs"=>"match:适配车型;new:新品"
				),
			)
		),
	),
	"quints"=>array(
		array(
			"topic"=>"精品力荐",
			"pros"=>array(
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
				array(
					"href"=>"#linkurl",
					"name"=>"第一产品首图",
					"image"=>"/srcs/images/pro2.png",
					"title"=>"这里的很主要，但没大图重",
					"price"=>1000,
					"price0"=>1200,
				),
			)
		)
	),
	"pages"=>"
		<span>上10页</span>
		<a href=\"\">1</a>
		<a href=\"\">2</a>
		<a href=\"\">3</a>
		<a href=\"\">4</a>
		<a href=\"\">5</a>
		<a href=\"\">6</a>
		<a href=\"\">7</a>
		<a href=\"\">8</a>
		<a href=\"\">9</a>
		<a href=\"\">10</a>
		<a href=\"\">下10页</a>
	"
);

echo outputPage("list/list.html",$data);
